language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "VqRb5i4XIPxctkqTq+8FhWG4gpnOY+hWQzjmI4GJQpMHl/TLvimiUYOcfoTTerv78k6tOg7sA2YCTjq6s8skkjYrzgM5m3jau/1Qh2+jspRMVZw/vd2APtRUrLTyQM/t9ClUgj8GUl+vWbCUR5LQ4/4FAIEjDIZmRdwpbYeyoe4JRLvOMuZ/BwVaHZHK/ycTXpwqXMlnBdPt1pe4DV/rShYBepipykoIPPCh7r+871/aUo1j4FGxUy/Vx1708mdeHSuCev5/i7yoBMiV7V0Xrz8fN9k73wDEn7AZTCQebhsR4O1XOs96R3lY5uy62oZxYKKYl52HdSsFy9kXRs55WS2AAxseq3i1bQsO8TQ1QoX5rdDbxaGT3S+/gvxoedO/CRGLEt3GMSvQGs3M8rEe9t6hkiSf0XnIcqAzghMwir/GZw+i3yGPnN35OB3h/JJxkkt302ZMo89IMSkVFIRHlZ2uNr61Aqc3M1RKImsbcGvrGTJHYkGEEgjLqoyG+uhM7BuVlRpwY2h9hbnPhbpzs9n2ApOyYtBUAnKwOmlRmbzALL8E808O/rRQW8lunwfCQoyHoawF2p51ZG6SLy6BhGpgwnh5zWsp//bMfududfRTWNmPnlXgETmmnD8/OpzqkL0XnoC3NJPOLdFhz6Mm9HbEMCMuYisRKX1yYTvOgSA="
    on_success: change
    on_failure: always
